apiVersion: apps/v1
kind: Deployment
metadata:
  name: safer-riskmodel
  labels:
    app: safer-riskmodel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safer-riskmodel
  template:
    metadata:
      labels:
        app: safer-riskmodel
    spec:
      containers:
        - name: safer-riskmodel-container
          image: python:3.11.5
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update -y &&
              git clone https://github.com/gachon-CCLab/safer-riskmodel.git /app &&
              python3 -m pip install -r /app/req.txt &&
              python3 /app/main.py
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: DANGEROUSLY_DISABLE_HOST_CHECK
              value: "true"
          ports:
            - containerPort: 8000
